//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementID { get; set; }
        public Nullable<int> AdvertisementGroupID { get; set; }
        public string AdvertisementTitle { get; set; }
        public Nullable<int> AdvertisementOrder { get; set; }
        public string AdvertisementUrl { get; set; }
        public bool AdvertisementIsActive { get; set; }
        public Nullable<System.DateTime> AdvertisementCreateDate { get; set; }
        public string AdvertisementImage { get; set; }
        public string AdvertisementImageUrl { get; set; }
    
        public virtual AdvertisementGroup AdvertisementGroup { get; set; }
    }
}
