//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblDocumentTree> TblDocumentTrees { get; set; }
        public DbSet<TblKeyValueAgr> TblKeyValueAgrs { get; set; }
        public DbSet<TblVisitTree> TblVisitTrees { get; set; }
        public DbSet<TblCodeTagPm> TblCodeTagPms { get; set; }
        public DbSet<TblShirkhat> TblShirkhats { get; set; }
        public DbSet<AdvertisementGroup> AdvertisementGroups { get; set; }
        public DbSet<Advertisement> Advertisements { get; set; }
        public DbSet<Agency> Agencies { get; set; }
        public DbSet<CassettePlayer> CassettePlayers { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<GalleryGroup> GalleryGroups { get; set; }
        public DbSet<LoginLog> LoginLogs { get; set; }
        public DbSet<Marquee> Marquees { get; set; }
        public DbSet<Newsletter> Newsletters { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<PageGroup> PageGroups { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<PaymentLog> PaymentLogs { get; set; }
        public DbSet<PaymentUniqueNumber> PaymentUniqueNumbers { get; set; }
        public DbSet<PhoneBookGroup> PhoneBookGroups { get; set; }
        public DbSet<PhoneBook> PhoneBooks { get; set; }
        public DbSet<ProductGroup> ProductGroups { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Propaganda> Propagandas { get; set; }
        public DbSet<RequestEvaluation> RequestEvaluations { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SendMail> SendMails { get; set; }
        public DbSet<SendSm> SendSms { get; set; }
        public DbSet<SiteSetting> SiteSettings { get; set; }
        public DbSet<SlideShow> SlideShows { get; set; }
        public DbSet<Software> Softwares { get; set; }
        public DbSet<TblChat> TblChats { get; set; }
        public DbSet<TblImei> TblImeis { get; set; }
        public DbSet<TblKeyValue> TblKeyValues { get; set; }
        public DbSet<TblPhotoList> TblPhotoLists { get; set; }
        public DbSet<TblVersionApp> TblVersionApps { get; set; }
        public DbSet<Track> Tracks { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<TblInspection> TblInspections { get; set; }
        public DbSet<TblManhol> TblManhols { get; set; }
        public DbSet<TblSpraying> TblSprayings { get; set; }
        public DbSet<TblStatement> TblStatements { get; set; }
        public DbSet<TblWash> TblWashes { get; set; }
        public DbSet<RasProductGroup> RasProductGroups { get; set; }
        public DbSet<RasProduct> RasProducts { get; set; }
        public DbSet<RasProductType> RasProductTypes { get; set; }
        public DbSet<TblAndroidLevel> TblAndroidLevels { get; set; }
        public DbSet<TblItem> TblItems { get; set; }
        public DbSet<TblProject> TblProjects { get; set; }
        public DbSet<TblStore> TblStores { get; set; }
        public DbSet<TblSubItem> TblSubItems { get; set; }
        public DbSet<TblSubItemAccess> TblSubItemAccesses { get; set; }
    }
}
