//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int GalleryId { get; set; }
        public int GalleryGroupsId { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public string GalleryImageUrl { get; set; }
        public string GalleryImageUrlThumb { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> GalleryOrder { get; set; }
    
        public virtual GalleryGroup GalleryGroup { get; set; }
    }
}
