//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryGroup
    {
        public GalleryGroup()
        {
            this.Galleries = new HashSet<Gallery>();
        }
    
        public int GalleryGroupId { get; set; }
        public string GalleryGroupTitle { get; set; }
        public Nullable<int> GalleryGroupOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
    }
}
