//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LogDatetime { get; set; }
        public string LogIp { get; set; }
        public short TypeLog { get; set; }
    
        public virtual User User { get; set; }
    }
}
