//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marquee
    {
        public int MarqueeID { get; set; }
        public string Title { get; set; }
        public string MarqueeUrl { get; set; }
        public bool IsActive { get; set; }
    }
}
