//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PageID { get; set; }
        public int PageGroupID { get; set; }
        public string PageTitle { get; set; }
        public string PageText { get; set; }
        public System.DateTime PageDate { get; set; }
        public string PageThumbnailImageUrl { get; set; }
        public long Visit { get; set; }
        public string Summary { get; set; }
        public string PageImageUrl { get; set; }
        public Nullable<int> PageOrder { get; set; }
        public bool HasComment { get; set; }
        public bool ActiveCommentAdmin { get; set; }
        public bool ActivePage { get; set; }
        public bool ActiveVisit { get; set; }
        public bool ActivePrint { get; set; }
        public bool ActivePageDate { get; set; }
        public bool IsSpecial { get; set; }
    
        public virtual PageGroup PageGroup { get; set; }
    }
}
