//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageGroup
    {
        public PageGroup()
        {
            this.PageGroups1 = new HashSet<PageGroup>();
            this.Pages = new HashSet<Page>();
        }
    
        public int PageGroupID { get; set; }
        public string PageGroupTitle { get; set; }
        public int PageGroupType { get; set; }
        public Nullable<int> PageGroupOrder { get; set; }
        public bool PageGroupIsActive { get; set; }
        public bool IsSubMenu { get; set; }
        public bool IsMenuLink { get; set; }
        public Nullable<int> PageGroupIDTree { get; set; }
    
        public virtual ICollection<PageGroup> PageGroups1 { get; set; }
        public virtual PageGroup PageGroup1 { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
    }
}
