//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public int PaymentLogID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string TrackingCode { get; set; }
        public string PaymentResponseCode { get; set; }
        public string PaymentResponseMessage { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<short> PaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<short> BankType { get; set; }
    
        public virtual User User { get; set; }
    }
}
