//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneBook
    {
        public int PhoneBookID { get; set; }
        public Nullable<int> PhoneBookGroupID { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Site { get; set; }
        public string PhoneNumber { get; set; }
        public string Comment { get; set; }
        public string Title { get; set; }
    
        public virtual PhoneBookGroup PhoneBookGroup { get; set; }
    }
}
