//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ProductImageID { get; set; }
        public int ProductID { get; set; }
        public string ProductImageUrl { get; set; }
        public string ProductThumbnailImageUrl { get; set; }
        public string ProductImageTitle { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
