//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            this.ProductGroups1 = new HashSet<ProductGroup>();
            this.Products = new HashSet<Product>();
        }
    
        public int ProductGroupID { get; set; }
        public string ProductGroupTitle { get; set; }
        public Nullable<int> ProductGroupOrder { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProductGroupIDTree { get; set; }
    
        public virtual ICollection<ProductGroup> ProductGroups1 { get; set; }
        public virtual ProductGroup ProductGroup1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
