//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RasProduct
    {
        public RasProduct()
        {
            this.TblStores = new HashSet<TblStore>();
        }
    
        public int ProductID { get; set; }
        public int ProductGroupID { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProductOrder { get; set; }
        public Nullable<int> ProductAvailable { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> ProductIdHardener { get; set; }
        public Nullable<int> ProductIdThinner { get; set; }
    
        public virtual RasProductGroup RasProductGroup { get; set; }
        public virtual RasProductType RasProductType { get; set; }
        public virtual ICollection<TblStore> TblStores { get; set; }
    }
}
