//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RasProductType
    {
        public RasProductType()
        {
            this.RasProducts = new HashSet<RasProduct>();
        }
    
        public int ProductTypeID { get; set; }
        public string ProductTypeTitle { get; set; }
    
        public virtual ICollection<RasProduct> RasProducts { get; set; }
    }
}
