//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RasProductGroup
    {
        public RasProductGroup()
        {
            this.RasProducts = new HashSet<RasProduct>();
            this.TblStores = new HashSet<TblStore>();
        }
    
        public int ProductGroupID { get; set; }
        public string ProductGroupTitle { get; set; }
        public Nullable<int> ProductGroupOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<RasProduct> RasProducts { get; set; }
        public virtual ICollection<TblStore> TblStores { get; set; }
    }
}
