//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSm
    {
        public int SendSmsID { get; set; }
        public string SmsText { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> TrackID { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
    }
}
