//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public int SiteSettingID { get; set; }
        public string MetaDescription { get; set; }
        public string Metakeywords { get; set; }
        public string WebSiteName { get; set; }
        public string WebSiteTitle { get; set; }
        public Nullable<short> SliderType { get; set; }
        public string IconImageUrl { get; set; }
        public string LogoImageUrl { get; set; }
        public string PhoneNumber { get; set; }
        public string YahooId { get; set; }
        public Nullable<short> PriceType { get; set; }
        public Nullable<int> Tax { get; set; }
        public bool SpecialProducts { get; set; }
        public bool NewProducts { get; set; }
        public bool PopularProducts { get; set; }
        public bool Propaganda { get; set; }
        public bool PaymentGuarantee { get; set; }
        public bool ProductCategories { get; set; }
        public string AccountNumberOnline { get; set; }
        public bool Date { get; set; }
        public bool Prayer { get; set; }
        public bool FlashClocks { get; set; }
        public bool Translate { get; set; }
        public bool Weather { get; set; }
        public string SendMailHost { get; set; }
        public string SendMailUserName { get; set; }
        public string SendMailPassword { get; set; }
        public bool SendMailEnableSsl { get; set; }
        public string HtmlTemplateMail { get; set; }
        public bool ThemeChange { get; set; }
        public bool FixHeaderTop { get; set; }
    }
}
