//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideShow
    {
        public int SlideShowID { get; set; }
        public string SlideShowTitle { get; set; }
        public string SlideShowSubTitle { get; set; }
        public string SlideShowImageUrl { get; set; }
        public string SlideShowHref { get; set; }
    }
}
