//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int SoftwareID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SoftwareName { get; set; }
        public string SoftwareEnName { get; set; }
        public short SoftwareStatus { get; set; }
        public bool OperatingSystemWin { get; set; }
        public bool OperatingSystemWeb { get; set; }
        public bool OperatingSystemAndroid { get; set; }
        public bool OperatingSystemIOS { get; set; }
        public bool OperatingSystemWinMobile { get; set; }
        public bool OperatingSystemLinux { get; set; }
        public short SoftwareUserLicense { get; set; }
        public Nullable<short> SoftwarePriceType { get; set; }
        public Nullable<int> SoftwarePrice { get; set; }
        public bool HowBuyPerson { get; set; }
        public bool HowBuyOnline { get; set; }
        public bool HowBuyShop { get; set; }
        public string SoftwareWebSite { get; set; }
        public string SoftwareImageLogoUrl { get; set; }
        public string SoftwareSummary { get; set; }
        public string SoftwareFullDescription { get; set; }
        public string SoftwareAdvantage { get; set; }
        public string OperatingSystemWinText { get; set; }
        public string OperatingSystemWebText { get; set; }
        public string OperatingSystemAndroidText { get; set; }
        public string OperatingSystemIOSText { get; set; }
        public string OperatingSystemWinMobileText { get; set; }
        public Nullable<double> SoftwareUserRating { get; set; }
        public int SoftwareVisit { get; set; }
        public Nullable<System.DateTime> DateTimeLastEdit { get; set; }
    
        public virtual User User { get; set; }
    }
}
