//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAndroidLevel
    {
        public int TblAndroidLevelId { get; set; }
        public int TblSubItemAccessId { get; set; }
        public Nullable<int> KeyID1 { get; set; }
        public Nullable<int> KeyID2 { get; set; }
        public Nullable<double> Metraj { get; set; }
        public Nullable<System.DateTime> DateDo { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<double> Thinner { get; set; }
        public Nullable<double> Hardener { get; set; }
        public Nullable<double> Color { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TblProjectId { get; set; }
        public Nullable<int> TblItemId { get; set; }
        public Nullable<int> TblSubItemId { get; set; }
    
        public virtual User User { get; set; }
    }
}
