//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCodeTagPm
    {
        public TblCodeTagPm()
        {
            this.TblShirkhats = new HashSet<TblShirkhat>();
        }
    
        public int TblCodeTagPmId { get; set; }
        public string CodeTag { get; set; }
        public string CodePm { get; set; }
    
        public virtual ICollection<TblShirkhat> TblShirkhats { get; set; }
    }
}
