//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocumentTree
    {
        public TblDocumentTree()
        {
            this.TblVisitTrees = new HashSet<TblVisitTree>();
        }
    
        public int TblDocumentTreeId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public string Address { get; set; }
        public Nullable<double> Pelak { get; set; }
        public Nullable<int> YearPlanting { get; set; }
        public Nullable<short> MantagheShahrdari { get; set; }
        public Nullable<short> TreeType { get; set; }
        public Nullable<int> TblUserId { get; set; }
    
        public virtual ICollection<TblVisitTree> TblVisitTrees { get; set; }
    }
}
