//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblItem
    {
        public TblItem()
        {
            this.TblSubItems = new HashSet<TblSubItem>();
        }
    
        public int TblItemId { get; set; }
        public int TblProjectId { get; set; }
        public int ItemCode { get; set; }
        public string Title { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
    
        public virtual TblProject TblProject { get; set; }
        public virtual ICollection<TblSubItem> TblSubItems { get; set; }
    }
}
