//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInspection
    {
        public int TblInspectionId { get; set; }
        public int TblManholId { get; set; }
        public Nullable<int> TblUserId { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<short> NeedHamsatSazi { get; set; }
        public Nullable<short> NeedBazsazi { get; set; }
        public Nullable<short> NeedShostosho { get; set; }
        public Nullable<short> NeedSampashi { get; set; }
        public Nullable<short> StatusPashne { get; set; }
        public Nullable<short> StatusMahiche { get; set; }
        public Nullable<int> VaziatManhole { get; set; }
        public Nullable<int> TypeManhole { get; set; }
        public Nullable<int> JenseManhole { get; set; }
    
        public virtual TblManhol TblManhol { get; set; }
    }
}
