//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblManhol
    {
        public TblManhol()
        {
            this.TblInspections = new HashSet<TblInspection>();
        }
    
        public int TblManholId { get; set; }
        public string CodeTag { get; set; }
        public Nullable<int> CodePm { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> DateSakht { get; set; }
        public Nullable<System.DateTime> DateNasb { get; set; }
        public Nullable<System.DateTime> DateBahrebardari { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public Nullable<int> CodeNaheyeh { get; set; }
        public string Address { get; set; }
        public Nullable<short> VaziatZaheri1 { get; set; }
        public Nullable<short> VaziatZaheri2 { get; set; }
        public Nullable<short> VaziatZaheri3 { get; set; }
        public Nullable<short> JenseDaricheh { get; set; }
        public Nullable<short> GhotrDariche { get; set; }
        public Nullable<int> CodeMakani { get; set; }
        public Nullable<int> CodeGis { get; set; }
        public Nullable<int> OmgheManhol { get; set; }
        public Nullable<int> GhotreManhol { get; set; }
        public Nullable<short> NoeManhol { get; set; }
        public Nullable<short> JenseManhol { get; set; }
        public Nullable<int> GhotreLolehVorodi { get; set; }
        public Nullable<int> GhotreLolehKhoroji { get; set; }
        public Nullable<int> TedadLoleVorodi { get; set; }
        public Nullable<short> Pelekan1 { get; set; }
        public Nullable<short> Pelekan2 { get; set; }
        public Nullable<short> SamPashi { get; set; }
        public Nullable<short> BandKeshi { get; set; }
        public Nullable<short> LiRobi { get; set; }
        public Nullable<short> Mahicheh { get; set; }
        public Nullable<short> Pashneh { get; set; }
        public string CodeEshterak { get; set; }
        public string Comment { get; set; }
        public string MehvarName { get; set; }
        public Nullable<int> TblUserId { get; set; }
        public Nullable<int> CodeSystem { get; set; }
        public Nullable<int> CodeCompany { get; set; }
        public Nullable<int> MapOld { get; set; }
        public Nullable<int> MapNew { get; set; }
        public Nullable<int> CodeTasfieKhane { get; set; }
        public Nullable<int> MantagheShahrdari { get; set; }
        public Nullable<int> MantagheGaz { get; set; }
        public Nullable<int> MantagheBargh { get; set; }
        public Nullable<int> MantagheMohakhaberat { get; set; }
        public Nullable<int> MantagheRanandegi { get; set; }
    
        public virtual ICollection<TblInspection> TblInspections { get; set; }
    }
}
