//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProject
    {
        public TblProject()
        {
            this.TblItems = new HashSet<TblItem>();
            this.TblStores = new HashSet<TblStore>();
        }
    
        public int TblProjectId { get; set; }
        public int ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string KarfarmaName { get; set; }
        public string PeimanKarName { get; set; }
        public string SarparastKargahName { get; set; }
        public string PeimanKarJozName { get; set; }
        public string ModirProjectName { get; set; }
        public Nullable<System.DateTime> DateStartPeiman { get; set; }
        public Nullable<System.DateTime> DateStartGharardad { get; set; }
        public string AddressKarfarma { get; set; }
        public string AddressProject { get; set; }
        public string NazerAliName { get; set; }
        public string NazerAliPhone { get; set; }
        public bool IsGoogleMap { get; set; }
    
        public virtual ICollection<TblItem> TblItems { get; set; }
        public virtual ICollection<TblStore> TblStores { get; set; }
    }
}
