//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPhotoList
    {
        public int TblPhotoListId { get; set; }
        public int ItemId { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbnailImageUrl { get; set; }
    }
}
