//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSpraying
    {
        public int TblSprayingId { get; set; }
        public int TblManholId { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
    }
}
