//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblShirkhat
    {
        public int TblShirkhatId { get; set; }
        public Nullable<int> TblCodeTagPmId { get; set; }
        public string SizeDariceh { get; set; }
        public string SizeOtaghak { get; set; }
        public string Status { get; set; }
        public Nullable<short> VaziatZaheri { get; set; }
        public Nullable<short> OtaghakType { get; set; }
        public Nullable<short> StatusMode { get; set; }
        public Nullable<short> VaziatDaricheh { get; set; }
        public Nullable<short> VaziatShir { get; set; }
        public Nullable<short> VaziatPelak { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TblUserId { get; set; }
        public Nullable<System.DateTime> DateTimeSabt { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Address { get; set; }
    
        public virtual TblCodeTagPm TblCodeTagPm { get; set; }
    }
}
