//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStatement
    {
        public int TblStatementID { get; set; }
        public Nullable<int> BasicPrice { get; set; }
        public Nullable<int> FactorPelosi { get; set; }
        public Nullable<int> FactorYear { get; set; }
        public Nullable<int> Complication { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
