//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStore
    {
        public int TblStoreId { get; set; }
        public int TblProjectId { get; set; }
        public int ProductGroupID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Ral { get; set; }
        public bool IsOutStore { get; set; }
        public Nullable<int> TblAndroidLevelId { get; set; }
    
        public virtual RasProductGroup RasProductGroup { get; set; }
        public virtual RasProduct RasProduct { get; set; }
        public virtual TblProject TblProject { get; set; }
    }
}
