//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubItemAccess
    {
        public int TblSubItemAccessId { get; set; }
        public int TblSubItemId { get; set; }
        public string Title { get; set; }
        public int KeyID1 { get; set; }
        public int KeyID2 { get; set; }
        public string Ral { get; set; }
    
        public virtual TblSubItem TblSubItem { get; set; }
    }
}
