//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVersionApp
    {
        public int TblVersionApp1 { get; set; }
        public string AppName { get; set; }
        public string Version { get; set; }
        public bool IsAndroid { get; set; }
    }
}
