//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVisitTree
    {
        public int TblVisitTreeId { get; set; }
        public int TblDocumentTreeId { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Diversion { get; set; }
        public Nullable<double> Environment { get; set; }
        public Nullable<short> Pest { get; set; }
        public Nullable<short> Sickness { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public Nullable<int> TblUserId { get; set; }
    
        public virtual TblDocumentTree TblDocumentTree { get; set; }
    }
}
