//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IranSoftjo.Package.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Agencies = new HashSet<Agency>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.Orders = new HashSet<Order>();
            this.PaymentLogs = new HashSet<PaymentLog>();
            this.Propagandas = new HashSet<Propaganda>();
            this.Softwares = new HashSet<Software>();
            this.TblChats = new HashSet<TblChat>();
            this.TblAndroidLevels = new HashSet<TblAndroidLevel>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string UserImageUrl { get; set; }
        public int AccountBalance { get; set; }
        public string WebSite { get; set; }
        public string Fax { get; set; }
        public Nullable<int> TblProjectId { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<System.DateTime> LastDateOnline { get; set; }
    
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PaymentLog> PaymentLogs { get; set; }
        public virtual ICollection<Propaganda> Propagandas { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Software> Softwares { get; set; }
        public virtual ICollection<TblChat> TblChats { get; set; }
        public virtual ICollection<TblAndroidLevel> TblAndroidLevels { get; set; }
    }
}
